apiVersion: v1
kind: Service
metadata:
  name: {{ include "dz6.fullname" . }}
  labels:
    {{- include "dz6.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: service-http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: service-metrics
  selector:
    {{- include "dz6.selectorLabels" . | nindent 4 }}
